name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install --force

      - name: Build Project
        run: npm run build

      - name: Show current working directory
        run: pwd

      - name: List 'my-website' directory contents
        run: ls -alh my-website

      - name: List dist folder contents
        run: ls -alh my-website/my-website/dist # Correct path to dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: my-website/my-website/dist # Correct path to the dist folder
